### ISSUE TITLE
Errors caused by indexing.yml file

### ISSUE THREAD

**Issue by Emil-io** [deepset-ai/hayhooks#13]
I created a hayhooks, haystack and opensearch setup (see this [github repo](https://github.com/Emil-io/opensarch_hayhooks/tree/main)).

Both the query and the indexing yaml are created by dumping a working pipeline config in python.

The problem seems to be caused by the indexing.yml - Once i leave this file out, the query pipeline works without a problem.

Could you help me find the issues here? Error message I am getting when accessing the localhost under "http://0.0.0.0:1416/docs":

> 2024-04-29 13:38:03     json_schema = generate_for_schema_type(schema_or_field)
> 2024-04-29 13:38:03   File "/opt/venv/lib/python3.10/site-packages/pydantic/json_schema.py", line 765, in is_instance_schema
> 2024-04-29 13:38:03     return self.handle_invalid_for_json_schema(schema, f'core_schema.IsInstanceSchema ({schema["cls"]})')
> 2024-04-29 13:38:03   File "/opt/venv/lib/python3.10/site-packages/pydantic/json_schema.py", line 2093, in handle_invalid_for_json_schema
> 2024-04-29 13:38:03     raise PydanticInvalidForJsonSchema(f'Cannot generate a JsonSchema for {error_info}')
> 2024-04-29 13:38:03 pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.IsInstanceSchema (<class 'pandas.core.frame.DataFrame'>)
> 2024-04-29 13:38:03
> 2024-04-29 13:38:03 For further information visit https://errors.pydantic.dev/2.6/u/invalid-for-json-schema
>

**Comment by lohit8846** [comment]
I've also seen the same issue with other types of data. Basically the pipeline execution still works, but cannot generate the docs due to this json schema generation failing

`pydantic.errors.PydanticInvalidForJsonSchema: Cannot generate a JsonSchema for core_schema.IsInstanceSchema (<class 'haystack.dataclasses.sparse_embedding.SparseEmbedding'>)
`

**Comment by lohit8846** [comment]
I believe this pull request tries to address a similar problem. https://github.com/deepset-ai/hayhooks/pull/7

**Comment by silvanocerza** [comment]
This is fixed with #7 and version `0.0.13`.

Remember to use latest Haystack version so it works properly, I had to fix a small thing there too.
