### ISSUE TITLE
Having issues in docker adding components

### ISSUE THREAD

**Issue by jacksteussie** [deepset-ai/hayhooks#14]
I've added a mount to the folder in my docker compose file containing my properly constructed custom components, but it doesn't  seem to work. I can attach different files as needed, just let me know what you think will help. Any help is appreciated!

**Comment by masci** [comment]
Hi @jacksteussie 

this is most likely due to a serialization problem in the I/O of your pipeline. If you post a minimal example to reproduce and/or the error you get, that would help.

**Comment by jacksteussie** [comment]
I actually solved this thank you!
