### ISSUE TITLE
issues with Hayhooks docker image

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/hayhooks#17]
`docker pull deepset/hayhooks`

fails:

```
Using default tag: latest
Error response from daemon: manifest for deepset/hayhooks:latest not found: manifest unknown: manifest unknown
```

**Comment by masci** [comment]
This is by design, the image doesn't support the `latest` tag, see https://vsupalov.com/docker-latest-tag/.

There was a problem in any case, the `main` tag wasn't updated correctly, that was fixed in 6c798b00
