### ISSUE TITLE
Enhance `/` endpoint

### ISSUE THREAD

**Issue by srini047** [deepset-ai/hayhooks#5]
Currently if the server starts I go to `http://localhost:1416/` which is the root of the server. But I get a empty response, which seems unsatisfying. Instead better to have a message to showcase.

Modifications to be done here: https://github.com/deepset-ai/hayhooks/blob/ee9150c2711e3c088306be65b96dbdb0d31066da/src/hayhooks/server/app.py#L37

I would like to take up this issue if that's fine.

**Comment by masci** [comment]
Hi @srini047 what info would you expect to see? Let's agree on what to show and I'll be happy to review a PR if you want to contribute the feature!

**Comment by srini047** [comment]
Sure @masci
Atleast a very basic response:
```json
{
  "message": "Sever is running"
}
```

Or something similar to the [Github API](https://api.github.com).
For Haystack equivalent:
```json
{
  "haystack_swagger_ui": "http://localhost:1416/docs",
  "haystack_deploy": "http://localhost:1416/deploy",
  "haystack_pipleine": "http://localhost:1416/pipeline",
}
```

Something like this. Which one do you prefer @masci?

**Comment by masci** [comment]
@srini047 the first one is very similar to the `/status` endpoint, so I'd go with the second, a "summary" of the available endpoints might be helpful indeed

**Comment by srini047** [comment]
> @srini047 the first one is very similar to the `/status` endpoint, so I'd go with the second, a "summary" of the available endpoints might be helpful indeed

@masci Is this fine?
```json
{
      "swagger_docs" : "http://localhost:1416/docs",
      "deploy_pipeline" : "http://localhost:1416/deploy",
      "draw_pipeline" : "http://localhost:1416/draw{/pipeline_name}",
      "server_status" : "http://localhost:1416/status",
      "undeploy_pipeline" : "http://localhost:1416/undeploy{/pipeline_name}",
  }
```
I tried covering all the endpoints. Is there anything missing?
